name: 2axios

on: workflow_dispatch

env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}



jobs  :
  Get-Branch-Info:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: get_branch

      - name: print Branch Name
        env:  
          #BRANCH_NAME: "${{ steps.get_branch.outputs.branch }}"
          BRANCH_NAME: "dagr100"
        run: echo $BRANCH_NAME

      - name: Get Channels
        shell: bash
        run: |

         echo "CHANNELS=yellow" >> "$GITHUB_ENV"

        id: get_channels


      - name: Echo Channels
        #run: echo "channels are here -- [${{ steps.get_channels.outputs.CHANNELS }}]"
        run: echo "${{ env.CHANNELS }}"




    
        



