name: Example of cURL action

on:
  pull_request:
    types:
      - closed

env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}


jobs:
  test-curl-action:
    name: "Perform REST API"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API 1"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: "https://api.replicated.com/vendor/v3/app/2QvaIsJs5IIA43vhEqrBfbqwbMf/channels"
          method: "GET"
          accept: 200, 201
          headers: '{ "Authorization": "e3beb38d236576afd11dca62d8018acb2879d245c7067e47db1947dac0778352" }'
          log-response: true
      - run: echo ${{ steps.api.outputs.response }}


      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        env:
          CHANNELS: ${{ steps.api.outputs.response }}"
        with:
          cmd: echo $CHANNELS  | jq -r --arg queryname 'dagr117' '.data.channels[] | select(.channelSlug == $queryname).id'

              

