name: Example of cURL action



on: workflow_dispatch

env:
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}
  dagr: https://api.replicated.com/vendor/v3/app/2QvaIsJs5IIA43vhEqrBfbqwbMf/channels

jobs:
  test-curl-action:
    name: "Perform REST API"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API 1"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: ${{ dagr }}
          method: "GET"
          accept: 201
          bearer-token: e3beb38d236576afd11dca62d8018acb2879d245c7067e47db1947dac0778352
          log-response: true
      - name: "Use response"
        run: echo ${{ steps.api.outputs.response }}