name: Example of cURL action

on: workflow_dispatch

env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}


jobs:
  test-curl-action:
    name: "Perform REST API"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API 1"
        uses: indiesdev/curl@v1.1
        id: api
        with:
          url: "https://api.replicated.com/vendor/v3/app/2QvaIsJs5IIA43vhEqrBfbqwbMf/channels"
          method: "GET"
          accept: 200, 201
          bearer-token: ${{ secrets.REPLICATED_API_TOKEN }}
          log-response: true
      - name: "Use response"
        env:
          stuff: "${{ steps.api.outputs.response }}"
        run: echo "here are the goods...$stuff"

