name: bar2

on: workflow_dispatch


jobs:

  build: # job id
    name: DemoJob # job name
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        id: hello # used below to refer to output from this step
        uses: actions/hello-world-javascript-action@master
        with: # specifies arguments to the action
          who-to-greet: 'Mark Volkmann'
      - name: Time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'