name: example

on: workflow_dispatch


env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}
  CHANNEL_ID: 2QvaIsJs5IIA43vhEqrBfbqwbMf


jobs:

  do-stuff:
    runs-on: ubuntu-latest
    outputs:
      CHANNELS: ${{ steps.get_channels.outputs.CHANNELS }}

    steps:

    - name: "Example output creation"
      id: "my_step"
      shell: bash
      run: |
        echo "CHANNELS=`curl --request GET --url https://api.replicated.com/vendor/v3/app/2QvaIsJs5IIA43vhEqrBfbqwbMf/channels --header 'Authorization: e3beb38d236576afd11dca62d8018acb2879d245c7067e47db1947dac0778352' --header 'accept: application/json'`" >> $GITHUB_OUTPUT

        #echo "Output [$CHANNELS]"
        #echo "CHANNELS=$CHANNELS" >> $GITHUB_OUTPUT   

    - name: Get Channel
      id: get_channel
      env:
        CHANNELS: ${{ steps.my_step.outputs.CHANNELS }}
      run: |
        echo "CHANNEL=`echo ${{ steps.my_step.outputs.CHANNELS }} | jq -r --arg queryname 'dagr' '.channels[] | select(.channelSlug == $queryname).channelSlug'`"
        echo $CHANNELS
      
