name: example

on: workflow_dispatch


env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}
  CHANNEL_ID: 2QvaIsJs5IIA43vhEqrBfbqwbMf


jobs:

  do-stuff:
    runs-on: ubuntu-latest
    outputs:
      CHANNELS: ${{ steps.get_channels.outputs.CHANNELS }}

    steps:

    - name: "Example output creation"
      id: "my_step"
      run: |
        my_var="Hello World"
        echo "Output [$my_var]"
        echo "my_var=$my_var" >> $GITHUB_OUTPUT   

    - name: "Example output call between steps"
      run: |
        echo "Output [${{steps.my_step.outputs.my_var}}]" 







