name: foo

on: workflow_dispatch

jobs:


  curl:
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: get_branch

    - name: Delete Channel
      uses: wei/curl@v1
      with:
        args: " --request DELETE --url https://api.replicated.com/vendor/v3/app//channel/2RpwcsKIGkm53opdtwxagFCZoia --header 'Authorization: b68065ed1ec4303b40b27a12ff3676ea7040f18b59dacdbf2db9e094260546cb"



