name: foo

on:
  pull_request:
    types:
      - closed

env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}
  CHANNEL_ID: 2Rq9GJaOgXEuEvq4laz6lXpvhVi

jobs:


  curl:
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: get_branch

    - name: print Branch Name
      env:
        BRANCH_NAME: "${{ steps.get_branch.outputs.branch }}"
      run: echo $BRANCH_NAME

    - name: Get Channels
      uses: wei/curl@v1
      with:
        args: "--request GET --url https://api.replicated.com/vendor/v3/app/$REPLICATED_APP_ID/channels --header 'Authorization: e3beb38d236576afd11dca62d8018acb2879d245c7067e47db1947dac0778352' --header 'accept: application/json'"
      id: get_channels

    - name: Get Channel ID
      env:
        GetChannels: "${{ steps.get_channels.outputs.channels }}"
      run: echo "channels are -- $GetChannels"









