name: foo

on: workflow_dispatch

jobs:


  curl:
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: get_branch

    - name: Delete Channel
      uses: wei/curl@v1
      with:
        args: "--request DELETE --url https://api.replicated.com/vendor/v3/app/2QvaIsJs5IIA43vhEqrBfbqwbMf/channel/2Rq8ScC9suzsH5dYF4uWHsRbDD2 --header 'Authorization: e3beb38d236576afd11dca62d8018acb2879d245c7067e47db1947dac0778352'"





