name: archive-vendor-port-channel-on-PR-close

on:
  pull_request:
    types:
      - closed

env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}
  

jobs: 
  archive-vendor-channel:
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: get_branch
      
    - name: archive-channel
      shell: bash
      run: |
        set +e

        # set variables
        BRANCH_NAME="${{ steps.get_branch.outputs.branch }}"
        echo "Branch name is: $BRANCH_NAME"
        AUTH="Authorization: $REPLICATED_API_TOKEN"

        CHANNEL_ID=`curl --request GET --url https://api.replicated.com/vendor/v3/app/"$REPLICATED_APP_ID"/channels --header "$AUTH" --header 'accept: application/json'  | jq -r --arg queryname $BRANCH_NAME '.channels[] | select(.channelSlug == $queryname).id'`

        # Archive channel
        if [ -n "$CHANNEL_ID" ]; then
              echo "Channel $CHANNEL_NAME exists in vendor portal app slug"
              echo "Channel_ID is: $CHANNEL_ID"

            RESPONSE=$(curl --request DELETE --url https://api.replicated.com/vendor/v3/app/"$REPLICATED_APP_ID"/channel/$CHANNEL_ID --header "$AUTH")

            if [[ "$RESPONSE" -ne 200 ]]; then
                echo ""
                echo "Results: Something went wrong; $CHANNEL_NAME exists but was not archived"
            else
                echo ""
                echo "Results: $BRANCH_NAME channel successfully archived"
            fi
        else
          echo ""
          echo "Results: $BRANCH_NAME channel does not exist in Replicated Vendor Portal app slug"
        fi




