name: archive-vendor-port-channel-on-PR-close

on:
  pull_request:
    types:
      - closed

env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  

jobs:
  archive-vendor-channel:
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: get_branch
      
    - name: archive-channel
      shell: bash
      run: |
        set +e
        # Download / install replicated cli
        curl -s https://api.github.com/repos/replicatedhq/replicated/releases/latest \
        | grep "browser_download_url.*linux_amd64.tar.gz" \
        | cut -d : -f 2,3 \
        | tr -d \" \
        | wget -O replicated.tar.gz -qi -
        tar xf replicated.tar.gz replicated && rm replicated.tar.gz
        mv replicated /usr/local/bin/replicated

        # set variables
        BRANCH_NAME="${{ steps.get_branch.outputs.branch }}"
        echo "Branch name is: $BRANCH_NAME"
        CHANNEL_NAME=`replicated channel ls | grep $BRANCH_NAME | awk '{ print $2 }'`
        CHANNEL_ID=`replicated channel ls | grep $BRANCH_NAME | awk '{ print $1 }'`

        # Archive channel
        if [ -n "$CHANNEL_NAME" ]; then
              echo "Channel $CHANNEL_NAME exists in vendor portal app slug"
              echo "Channel_ID is: $CHANNEL_ID"

              replicated channel rm $CHANNEL_ID
            if [ $? -ne 0 ]; then
              echo ""
              echo "Results: Something went wrong; $CHANNEL_NAME exists but was not archived"
              else
              echo ""
              echo "Results: $BRANCH_NAME channel successfully archived"
            fi
        else
          echo ""
          echo "Results: $BRANCH_NAME channel does not exist in Replicated Vendor Portal app slug"
        fi




