name: channel-output

on: workflow_dispatch


env:
  REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.REPLICATED_APP }}
  REPLICATED_APP_ID: ${{ secrets.REPLICATED_APP_ID }}
  CHANNEL_ID: 2QvaIsJs5IIA43vhEqrBfbqwbMf


jobs:

  do-stuff:
    runs-on: ubuntu-latest
    outputs:
      CHANNEL_NAME: ${{ steps.get_channels.outputs.CHANNEL_NAME}}

    steps:

    - name: Get branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: get_branch

    - name: print Branch Name
      env:  
        BRANCH_NAME: "${{ steps.get_branch.outputs.branch }}"
      run: echo $BRANCH_NAME

    - name: Get Channels
      shell: bash
      id: get_channels
      run: "curl --request GET --url https://api.replicated.com/vendor/v3/app/2QvaIsJs5IIA43vhEqrBfbqwbMf/channels --header 'Authorization: e3beb38d236576afd11dca62d8018acb2879d245c7067e47db1947dac0778352' --header 'accept: application/json'"   

    - name: Print channel
      run: jq -r --arg queryname "dagr" '.channels[] | select(.channelSlug == $queryname).channelSlug' echo 'CHANNEL_NAME={}' >> $GITHUB_OUTPUT ';'
         













