name: kung-phooey

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: echo '{"fruit":{"name":"apple","color":"green","price":1.20}}' | jq '.'


      
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'