name: printenv
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: printenv
        run: printenv      
      - name: branch
        run: echo $branch
      - name: print goodbye
        run: echo "bye..."
    
